### ISSUE TITLE
Fix voor je snoepomhoog menu

### ISSUE THREAD

**Issue by KaanKalmi** [saschavanvliet/the-startup-responsive-interactieve-website#10]
<img height=300px src="https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/assets/144000125/fa4bda6c-cffd-4fdf-851e-de8e595abe00">

Je hebt hier `position:absolute;` gegeven aan je dropdown menu, dit zorgde ervoor dat als je op t icoontje klikte voor overlapping.

Wat je ipv dat wilt doen is:
<img height=300px src="https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/assets/144000125/c582275f-eb32-45e8-b508-1e5589b4e2f7">
Je ziet hier dat ik namelijk de `position:absolute;` heb weggehaald en de `height` heb verandert naar 0, daarnaast heb ik `overflow: hidden;` erin gezet !DIT IS BELANGRIJK! dit zorgt er namelijk voor dat je menu niet gezien wordt nog.

Hierna wil je een class erin zetten en koppelen via JS voor de interactie, dit had je al gedaan dus heb ik alleen de class .active verandert,
Hier heb ik de `display:block;` gezet, `height:auto;` en `margin-top` zodat er geen overlapping mogelijk is

**Comment by saschavanvliett** [comment]
Omg echt super bedankt!!!! Dit is echt precies wat ik nodig had :)))))))))))) !!
