### ISSUE TITLE
<a> in een button

### ISSUE THREAD

**Issue by lisavanmansom** [saschavanvliet/the-startup-responsive-interactieve-website#11]
Je heb 1 error in je HTML validator.

https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/blob/4bbb52f69657da2fe32457c3b016153de0e4a21b/index.html#L50

Op line 50 heb je een a in een button wat niet correct lijkt te zijn. Het is misschien beter om alleen het <a> element te gebruiken en de <button> element weg te laten. Je zou dan de link kunnen stylen als een button waardoor het hetzelfde effect kan geven aan de gebruiker

<img width="1214" alt="Scherm­afbeelding 2024-01-19 om 11 32 27" src="https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/assets/144007419/177dcb09-acba-4cc0-99d6-1962fab3f276">

Bron die je kan bekijken: https://www.freecodecamp.org/news/html-button-link-code-examples-how-to-make-html-hyperlinks-using-the-href-attribute-on-tags/

**Comment by saschavanvliett** [comment]
Het duurde even, maar door je toegevoegde link kon ik het goed oplossen!
