### ISSUE TITLE
Ongebruikte CSS-regels:

### ISSUE THREAD

**Issue by RubenErhardt** [saschavanvliet/the-startup-responsive-interactieve-website#13]
De CSS bevat stijlen voor een klasse .blue-section die niet aanwezig is in je HTML. Als het niet bedoeld is voor gebruik, kun je deze regels verwijderen.

```.blue-section {
    height: 21em;
    background-color: #001717;
    display: flex;
    align-items: center;
    flex-direction: column;
    min-height: 20em;
    max-width: 414px;
  }```

**Comment by RubenErhardt** [comment]
.blue-section {
    height: 21em;
    background-color: #001717;
    display: flex;
    align-items: center;
    flex-direction: column;
    min-height: 20em;
    max-width: 414px;
  }

**Comment by saschavanvliett** [comment]
Ohja, helemaal vergeten weg te halen. Bedankt!
