### ISSUE TITLE
In de link ontbreekt <a> <href>

### ISSUE THREAD

**Issue by Akikosophia** [saschavanvliet/the-startup-responsive-interactieve-website#14]
In de link ontbreekt <a> <href> 

link data-color-theme="dark_dimmed" crossorigin="anonymous" media="all" rel="stylesheet" data-href="https://github.githubassets.com/assets/dark_dimmed-b2e1b478d5b4.css"

Je kunt dit voorbeeld gebruiken en de link van de url aanpassen!

<a href="https://www.w3schools.com/">Visit W3Schools.com!</a>

Hieronder de link met meer informatie:

https://www.w3schools.com/html/html_links.asp

**Comment by saschavanvliett** [comment]
Dit was het thema van mijn vs code hahhaahaha, maar wel bedankt :)
