### ISSUE TITLE
Class naamgeving

### ISSUE THREAD

**Issue by lisavanmansom** [saschavanvliet/the-startup-responsive-interactieve-website#15]
https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/blob/4bbb52f69657da2fe32457c3b016153de0e4a21b/style.css#L26-L28

Inplaats van .eerstefoto is het handig om een class een naam te geven met meer betekenis. Je zou bijvoorbeeld je classname zo noemen: ".container-1". En het dan selecteren in CSS met ".container-1 img {- styling code -}. De kans is namelijk dat uiteindelijk de '1e foto' een 2e /3e foto kan worden.

**Comment by saschavanvliett** [comment]
Ohja thanks! Is inderdaad een beetje vaag
