### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by Hadil66** [saschavanvliet/the-startup-responsive-interactieve-website#2]
Het is misschien slim om alle werknemersdata te gebruiken en niet om een paar uit te kiezen.

https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/blob/615d1963e6a285a705835462d3df9325052d249b/index.html#L74-L78

**Comment by saschavanvliett** [comment]
Na een tijdje achter de laptop gezeten te hebben alle namen erin gezet
