### ISSUE TITLE
dropdown menu

### ISSUE THREAD

**Issue by Hadil66** [saschavanvliet/the-startup-responsive-interactieve-website#3]
Goed dat je een dropdown menu heb gemaakt. Dat is een goed idee. Ik was het zelf vergeten.

https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/blob/615d1963e6a285a705835462d3df9325052d249b/style.css#L148-L164

**Comment by saschavanvliett** [comment]
Thankyou ;)
