### ISSUE TITLE
Geen consistente benaming

### ISSUE THREAD

**Issue by RubenErhardt** [saschavanvliet/the-startup-responsive-interactieve-website#4]
<button id="dropdownButton">-</button>
        <div id="dropdownMenu" class="dropdown-menu">

niet consistent in benaming

**Comment by RubenErhardt** [comment]
<button id="dropdownButton">-</button>
        <div id="dropdownMenu" class="dropdown-menu">

**Comment by RubenErhardt** [comment]
button id="dropdownButton">-</button
        div id="dropdownMenu" class="dropdown-menu"

**Comment by saschavanvliett** [comment]
Hoi, voor mij is het wel duidelijk wat het verschil is, dus voor nu laat ik het staan maar wel bedankt!
