### ISSUE TITLE
import fonts in the head zetten

### ISSUE THREAD

**Issue by RubenErhardt** [saschavanvliet/the-startup-responsive-interactieve-website#7]
<style>
        @import url('https://fonts.googleapis.com/css2?family=Expletus+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&family=Saira+Condensed:wght@400;700&family=Ubuntu:ital,wght@0,400;0,700;1,400&display=swap');
    </style>

zet dit is gwn even lekker in de head

**Comment by saschavanvliett** [comment]
Heb deze regel in de head gezet nu!
