### ISSUE TITLE
Nav in header + div? + semantiek

### ISSUE THREAD

**Issue by Naddybs** [saschavanvliet/the-startup-responsive-interactieve-website#9]
https://github.com/saschavanvliet/the-startup-responsive-interactieve-website/blob/615d1963e6a285a705835462d3df9325052d249b/index.html#L37-L47

Je nav kan je binnen een header element zetten. En de content binnen je navigatie zet je in een <nav> element.

voorbeeld standaard nav structuur:
<header>
   <nav>
        <ul>
            <li> menu</li>
            <li>contact</li>
            <li>geenidee</li>
       </ul>
  </nav>
</header>

- also: die div om je nav items heen is onnodig.
-probeer ook je html op volgorde te doen van hoe je content staat weergegeven voor beter overzicht. Vb blue section onder je nav.

**Comment by saschavanvliett** [comment]
Die div is voor de styling van het uitklapmenu. Zonder de div wordt het erg lastig. Voor de rest heb ik alles nu aangepast qua structuur. Dankjewel yuh
